# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre',
        ),
    ]
