# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170417_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellido',
            field=models.CharField(default='alvarito', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(default='Reyes', max_length=30),
            preserve_default=False,
        ),
    ]
