# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioUnidad', models.IntegerField()),
                ('valorVenta', models.IntegerField()),
                ('unidades', models.IntegerField()),
                ('impuesto', models.FloatField(max_length=30)),
            ],
        ),
    ]
