# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioUnidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valorVenta',
            field=models.FloatField(),
        ),
    ]
