# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20170415_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descontinuado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
