# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('nombreCompania', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(max_length=100)),
                ('concepto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoPagado', models.IntegerField()),
                ('fechaPago', models.DateField(max_length=100)),
                ('concepto', models.IntegerField()),
                ('montoTotal', models.IntegerField()),
                ('saldoAPagar', models.IntegerField()),
                ('nroCuotas', models.IntegerField()),
                ('idCuentaPorCobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.CuentaPorCobrar')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valorUnitario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=100)),
                ('subtotal', models.IntegerField()),
                ('ivaTotal', models.IntegerField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Empleado')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idSede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Sede'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura'),
        ),
    ]
