# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='concepto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallecuentaporcobrar',
            name='montoPagado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallecuentaporcobrar',
            name='montoTotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallecuentaporcobrar',
            name='saldoAPagar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='valorUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cedula',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='factura.Empleado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='ivaTotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='factura.Cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
