# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_auto_20170417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cedula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.Cliente'),
        ),
    ]
