# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20170417_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='fechaInicio',
        ),
        migrations.AlterField(
            model_name='factura',
            name='cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.Cliente'),
        ),
    ]
