# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCargo', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('nombreCompañia', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCuentaPorCobrar', models.IntegerField()),
                ('fechaInicio', models.DateField(max_length=100)),
                ('concepto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDetalleCuentaPorCobrar', models.IntegerField()),
                ('montoPagado', models.IntegerField()),
                ('fechaPago', models.DateField(max_length=100)),
                ('concepto', models.IntegerField()),
                ('montoTotal', models.IntegerField()),
                ('saldoAPagar', models.IntegerField()),
                ('nroCuotas', models.IntegerField()),
                ('idCuentaPorCobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.CuentaPorCobrar')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDetalleFactura', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('valorUnitario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(max_length=100)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFactura', models.IntegerField()),
                ('fecha', models.DateField(max_length=100)),
                ('subtotal', models.IntegerField()),
                ('ivaTotal', models.IntegerField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Empleado')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('precioUnidad', models.IntegerField()),
                ('valorVenta', models.IntegerField()),
                ('unidades', models.IntegerField()),
                ('impuesto', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSede', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idSede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Sede'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Factura'),
        ),
    ]
